# Generated by Django 5.1.15 on 2026-08-16 10:07

import apps.core.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_claimevidence_providerclaim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('raw_input', models.TextField(blank=True, help_text="The buyer's own words, before A1 structured them.")),
                ('structured', models.JSONField(blank=True, default=dict, help_text='A1 draft (CLAUDE.md rule 3). Never authoritative.')),
                ('is_ai_assisted', models.BooleanField(default=False, help_text='True when the form the buyer confirmed was pre-filled by A1.')),
                ('company_type', models.CharField(choices=[('hk_private_limited', 'Hong Kong private limited company'), ('hk_branch', 'Hong Kong branch of a non-HK company'), ('hk_rep_office', 'Representative office'), ('offshore', 'Offshore company'), ('undecided', 'Not decided yet')], default='hk_private_limited', max_length=24)),
                ('shareholder_nationalities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='ISO 3166-1 alpha-2.', size=None)),
                ('business_nature', models.CharField(blank=True, max_length=200)),
                ('services_needed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('incorporation', 'Company incorporation'), ('company_secretary', 'Company secretary'), ('registered_address', 'Registered address'), ('accounting', 'Accounting'), ('audit_liaison', 'Audit liaison'), ('bank_account_assist', 'Bank account assistance'), ('tax_filing', 'Tax filing'), ('trademark', 'Trademark'), ('work_visa', 'Work visa')], max_length=32), default=list, size=None)),
                ('needs_bank_account', models.BooleanField(default=False)),
                ('preferred_banks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Traditional bank'), ('virtual', 'Virtual bank'), ('emi', 'EMI / payment institution')], max_length=16), blank=True, default=list, size=None)),
                ('currency', models.CharField(default='HKD', max_length=3)),
                ('budget_min_minor', models.BigIntegerField(blank=True, null=True)),
                ('budget_max_minor', models.BigIntegerField(blank=True, null=True)),
                ('timeline', models.CharField(choices=[('asap', 'As soon as possible'), ('within_1_month', 'Within a month'), ('within_3_months', 'Within three months'), ('flexible', 'Flexible'), ('undecided', 'Not decided yet')], default='undecided', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for quotes'), ('closed', 'Closed by the buyer'), ('awarded', 'Awarded'), ('expired', 'Expired')], db_index=True, default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Visible on the request wall'), ('invited_only', 'Invited companies only')], default='public', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=200)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='HKD', max_length=3)),
                ('first_year_total_minor', models.BigIntegerField()),
                ('renewal_total_minor', models.BigIntegerField(blank=True, null=True)),
                ('includes_govt_fee', models.BooleanField(default=False, help_text='Whether the first-year total already contains government fees.')),
                ('delivery_days', models.PositiveSmallIntegerField(blank=True, help_text='Working days to delivery, as promised by the company.', null=True)),
                ('validity_days', models.PositiveSmallIntegerField(default=14)),
                ('message', models.TextField(blank=True)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('declined', 'Not selected'), ('withdrawn', 'Withdrawn by the company'), ('expired', 'Expired')], db_index=True, default='submitted', max_length=16)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='providers.provider')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_quotes', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='rfq.rfq')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotaLedger',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('free_used', models.PositiveSmallIntegerField(default=0)),
                ('paid_used', models.PositiveIntegerField(default=0)),
                ('paid_balance', models.PositiveIntegerField(default=0, help_text='Purchased quotes remaining at the end of this day.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_ledger', to='providers.provider')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'date'), name='rfq_one_ledger_row_per_day')],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('govt_incorporation_fee', 'Government incorporation fee'), ('business_registration_fee', 'Business registration fee'), ('incorporation_service', 'Incorporation service fee'), ('company_secretary', 'Company secretary (first year)'), ('registered_address', 'Registered address (first year)'), ('company_kit', 'Company kit and chops'), ('bank_account_assist', 'Bank account assistance'), ('annual_return', 'Annual return filing'), ('accounting', 'Accounting'), ('audit_liaison', 'Audit liaison'), ('courier', 'Courier and handling'), ('other', 'Other')], max_length=32)),
                ('custom_label', models.CharField(blank=True, help_text="Only meaningful when label is 'other'.", max_length=120)),
                ('amount_minor', models.BigIntegerField()),
                ('unit', models.CharField(choices=[('one_off', 'One-off'), ('yearly', 'Per year'), ('monthly', 'Per month'), ('hourly', 'Per hour'), ('estimate', 'Estimate only')], default='one_off', max_length=16)),
                ('is_optional', models.BooleanField(default=False, help_text='Excluded from the first-year total when true.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('ordinal', models.PositiveSmallIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='rfq.quote')),
            ],
            options={
                'ordering': ['ordinal', 'label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('label', 'other'), _negated=True), fields=('quote', 'label'), name='rfq_one_line_item_per_standard_label'), models.CheckConstraint(condition=models.Q(('amount_minor__gte', 0)), name='rfq_line_item_not_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', 'visibility', '-published_at'], name='rfq_rfq_status_f13a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', 'expires_at'], name='rfq_rfq_status_a9941b_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfq',
            constraint=models.CheckConstraint(condition=models.Q(('budget_min_minor__isnull', True), ('budget_max_minor__isnull', True), ('budget_max_minor__gte', models.F('budget_min_minor')), _connector='OR'), name='rfq_budget_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='rfq',
            constraint=models.CheckConstraint(condition=models.Q(('budget_min_minor__isnull', True), ('budget_min_minor__gte', 0), _connector='OR'), name='rfq_budget_min_not_negative'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['provider', '-submitted_at'], name='rfq_quote_provide_f560e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'withdrawn'), _negated=True), fields=('rfq', 'provider'), name='rfq_one_live_quote_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('first_year_total_minor__gte', 0)), name='rfq_quote_first_year_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('renewal_total_minor__isnull', True), ('renewal_total_minor__gte', 0), _connector='OR'), name='rfq_quote_renewal_not_negative'),
        ),
    ]
