# Generated by Django 5.1.15 on 2026-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='matches',
            field=models.JSONField(blank=True, default=dict, help_text='A2 suggestions. Never a permission and never a rank.'),
        ),
    ]
