# Generated by Django 5.1.15 on 2026-08-14 09:19

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('providers', '0002_claimevidence_providerclaim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMember',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='owner', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_memberships', to='providers.providerclaim')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='providers.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider member',
                'verbose_name_plural': 'provider members',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'is_active'], name='accounts_pr_provide_6c7b24_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='accounts_one_membership_per_provider')],
            },
        ),
    ]
