# Generated by Django 5.1.15 on 2026-08-20 06:03

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_providermember'),
        ('providers', '0005_providerlogoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMemberInvite',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='The address this invitation was sent to.', max_length=254)),
                ('member_role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_member_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_member_invites', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_invites', to='providers.provider')),
            ],
            options={
                'verbose_name': 'provider member invitation',
                'verbose_name_plural': 'provider member invitations',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'accepted_at'], name='accounts_pr_provide_a222a0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('provider', 'email'), name='accounts_one_open_invite_per_email')],
            },
        ),
    ]
