# Generated by Django 5.1.15 on 2026-08-13 09:04

import apps.core.models
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # The GIN indexes below use gin_trgm_ops for fuzzy name search, which
        # needs pg_trgm. Creating the extension requires a superuser; on Render
        # the database owner has rights to CREATE EXTENSION, see
        # docs/DEPLOY_RENDER.md.
        TrigramExtension(),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.CharField(max_length=512)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('aborted_sanity', 'Aborted by sanity check')], default='running', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('prev_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('raw_file_key', models.CharField(blank=True, max_length=512)),
                ('error', models.TextField(blank=True)),
                ('is_dry_run', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_zh', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField()),
                ('remarks_en', models.TextField(blank=True)),
                ('remarks_zh', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('raw', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['name_en'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='registry_name_en_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['name_zh'], name='registry_name_zh_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='LicenseeChange',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence_no', models.CharField(db_index=True, max_length=32)),
                ('change_type', models.CharField(choices=[('new', 'New licensee'), ('removed', 'Removed from register'), ('reactivated', 'Back on the register'), ('renamed', 'Name changed'), ('address_changed', 'Address changed')], max_length=20)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('ai_summary', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='registry.syncrun')),
            ],
            options={
                'ordering': ['licence_no'],
                'indexes': [models.Index(fields=['sync_run', 'change_type'], name='registry_li_sync_ru_32d5f2_idx')],
            },
        ),
    ]
