# Generated by Django 5.1.15 on 2026-08-18 11:34

import apps.core.models
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The column type does not exist until the extension does. No vector
        # index yet: `ivfflat` has to be sized to the row count, and there are
        # no embeddings to size it to until an embedding provider is configured
        # (DATA_MODEL "content").
        VectorExtension(),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('incorporation', 'Setting up a company'), ('banking', 'Opening a bank account'), ('licensing', 'Licences and how to check them'), ('fees', 'Fees and hidden costs'), ('compliance', 'Staying compliant')], db_index=True, max_length=32)),
                ('title_zh_hans', models.CharField(max_length=160)),
                ('title_zh_hant', models.CharField(blank=True, max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(max_length=400)),
                ('body_md', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.article')),
            ],
            options={
                'verbose_name': 'article chunk',
                'verbose_name_plural': 'article chunks',
                'ordering': ['article', 'ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('published_at__isnull', False), _connector='OR'), name='content_published_article_has_a_date'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('article', 'ordinal'), name='content_one_chunk_per_ordinal'),
        ),
    ]
