# Generated by Django 5.1.15 on 2026-08-13 10:12

import apps.core.models
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('claim_status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('pending', 'Claim pending'), ('claimed', 'Claimed'), ('rejected', 'Claim rejected')], db_index=True, default='unclaimed', max_length=16)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('verified', 'Verified'), ('premium', 'Premium')], db_index=True, default='free', max_length=16)),
                ('logo', models.FileField(blank=True, upload_to='providers/logos/')),
                ('website', models.URLField(blank=True)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('office_photos', models.JSONField(blank=True, default=list)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mandarin', 'Mandarin'), ('cantonese', 'Cantonese'), ('english', 'English')], max_length=16), blank=True, default=list, size=None)),
                ('supports_simplified', models.BooleanField(default=False)),
                ('remote_onboarding', models.BooleanField(default=False)),
                ('bank_account_support', models.BooleanField(default=False)),
                ('bank_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Traditional bank'), ('virtual', 'Virtual bank'), ('emi', 'EMI / payment institution')], max_length=16), blank=True, default=list, size=None)),
                ('non_resident_shareholder_experience', models.BooleanField(default=False)),
                ('industry_specialties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('rating_cached', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Published reviews, verified or not - what the review tab lists.')),
                ('verified_review_count', models.PositiveIntegerField(default=0, help_text='NNC1-verified reviews only - the number shown beside the score.')),
                ('profile_completeness', models.DecimalField(decimal_places=3, default=0, help_text='0-1, see services.py.', max_digits=4)),
                ('responsiveness_score', models.DecimalField(decimal_places=3, default=0, help_text='0-1, from RFQ reply times (P5).', max_digits=4)),
                ('ranking_score', models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='See services.py.', max_digits=6)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('commission_agreement', models.BooleanField(default=False, help_text='If true the page MUST render the disclosure (COMPLIANCE 6).')),
                ('licensee', models.OneToOneField(blank=True, help_text='Null only for a candidate that is not on the register; never published.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='registry.licensee')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('tcsp_licence', 'TCSP licence'), ('office_verified', 'Office verified'), ('website_verified', 'Website verified'), ('track_record', 'Track record'), ('premium_badge', 'Premium badge')], max_length=24)),
                ('verified_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_ref', models.CharField(blank=True, max_length=512)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='providers.provider')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('incorporation', 'Company incorporation'), ('company_secretary', 'Company secretary'), ('registered_address', 'Registered address'), ('accounting', 'Accounting'), ('audit_liaison', 'Audit liaison'), ('bank_account_assist', 'Bank account assistance'), ('tax_filing', 'Tax filing'), ('trademark', 'Trademark'), ('work_visa', 'Work visa')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='providers.provider')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('currency', models.CharField(default='HKD', max_length=3)),
                ('amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('min_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('max_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('one_off', 'One-off'), ('yearly', 'Per year'), ('monthly', 'Per month'), ('hourly', 'Per hour')], default='one_off', max_length=16)),
                ('includes_govt_fee', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('provider_declared', 'Declared by the provider'), ('quote_derived', 'Derived from quotes'), ('platform_survey', 'Platform survey')], default='provider_declared', max_length=24)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='providers.serviceoffering')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=django.contrib.postgres.indexes.GinIndex(fields=['industry_specialties'], name='providers_specialties_gin'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_published', 'tier'], name='providers_p_is_publ_0a4be3_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.UniqueConstraint(fields=('provider', 'category'), name='providers_one_offering_per_category'),
        ),
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__isnull', False), models.Q(('max_amount_minor__isnull', False), ('min_amount_minor__isnull', False)), _connector='OR'), name='providers_price_point_or_range'),
        ),
    ]
