# Generated by Django 5.1.15 on 2026-08-14 09:19

import apps.core.models
import apps.core.storage
import apps.providers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('business_registration', 'Business registration certificate'), ('address_proof', 'Proof of business address'), ('authorisation', 'Letter of authorisation'), ('other', 'Other supporting document')], default='business_registration', max_length=32)),
                ('file', models.FileField(storage=apps.core.storage.private_storage, upload_to=apps.providers.models.claim_evidence_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('extension', models.CharField(max_length=8)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Scan pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan error'), ('skipped', 'Scan skipped by a reviewer')], db_index=True, default='pending', max_length=16)),
                ('scan_detail', models.CharField(blank=True, max_length=255)),
                ('scanner', models.CharField(blank=True, max_length=32)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'claim evidence',
                'verbose_name_plural': 'claim evidence',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderClaim',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_registration_no', models.CharField(blank=True, max_length=32)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_role', models.CharField(blank=True, max_length=120)),
                ('applicant_note', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, help_text='The site the token is published on; may differ from the profile.')),
                ('website_verification_token', models.CharField(db_index=True, max_length=64)),
                ('website_verified_at', models.DateTimeField(blank=True, null=True)),
                ('website_verification_method', models.CharField(blank=True, max_length=16)),
                ('website_verification_log', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by the applicant')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal; never shown to the applicant.')),
                ('ai_risk_flags', models.JSONField(blank=True, default=dict, help_text='Advisory only (CLAUDE.md rule 3). Never decides.')),
            ],
            options={
                'verbose_name': 'provider claim',
                'verbose_name_plural': 'provider claims',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.UniqueConstraint(fields=('provider', 'type'), name='providers_one_certification_per_type'),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='scan_override_by',
            field=models.ForeignKey(blank=True, help_text='Set only when a reviewer accepted a file the scanner did not clear.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerclaim',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='providerclaim',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerclaim',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='providers.providerclaim'),
        ),
        migrations.AddIndex(
            model_name='providerclaim',
            index=models.Index(fields=['status', 'created_at'], name='providers_p_status_cf1283_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('provider',), name='providers_one_pending_claim_per_provider'),
        ),
    ]
