# Generated by Django 5.1.15 on 2026-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_claimevidence_providerclaim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='paid_placement_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
