# Generated by Django 5.1.15 on 2026-08-19 14:42

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_paid_placement_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_wechat',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, help_text='Published self-introduction. Set by moderation, never by a form.'),
        ),
        migrations.CreateModel(
            name='ProviderProfileEdit',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('applied', 'Applied immediately'), ('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=16)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('submitted_description', models.TextField(blank=True)),
                ('is_correction', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null once the account is deleted; the row and its diff remain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_edits', to='providers.provider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile edit',
                'verbose_name_plural': 'profile edits',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['provider', '-created_at'], name='providers_p_provide_2fc735_idx'), models.Index(fields=['status', '-created_at'], name='providers_p_status_df1303_idx')],
            },
        ),
    ]
