# Generated by Django 5.1.15 on 2026-08-20 05:48

import apps.core.models
import apps.core.storage
import apps.providers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_contact_email_provider_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLogoUpload',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=apps.core.storage.private_storage, upload_to=apps.providers.models.provider_logo_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('extension', models.CharField(max_length=8)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Scan pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan error'), ('skipped', 'Scan skipped by a reviewer')], db_index=True, default='pending', max_length=16)),
                ('scan_detail', models.CharField(blank=True, max_length=255)),
                ('scanner', models.CharField(blank=True, max_length=32)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Published'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by the company')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_uploads', to='providers.provider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider logo upload',
                'verbose_name_plural': 'provider logo uploads',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'created_at'], name='providers_p_status_c1fdfc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('provider',), name='providers_one_pending_logo_per_provider')],
            },
        ),
    ]
