# Generated by Django 5.1.15 on 2026-08-15 08:08

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=16)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('input_ref', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('invalid_schema', 'Invalid schema'), ('timeout', 'Timeout'), ('error', 'Error'), ('fallback', 'Fell back to rules')], db_index=True, default='ok', max_length=16)),
                ('fallback_reason', models.CharField(blank=True, choices=[('disabled', 'Agent switched off'), ('no_api_key', 'No API key configured'), ('budget', 'Daily budget spent'), ('api_error', 'API error after retries'), ('invalid_schema', 'Model returned unusable output'), ('timeout', 'Timed out')], db_index=True, max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'agent run',
                'verbose_name_plural': 'agent runs',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['agent_name', '-created_at'], name='agents_agen_agent_n_cf45ad_idx'), models.Index(fields=['object_type', 'object_id'], name='agents_agen_object__14c514_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentFeedback',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('correct', 'Correct'), ('partially', 'Partially correct'), ('wrong', 'Wrong')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'agent feedback',
                'verbose_name_plural': 'agent feedback',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('agent_run', 'reviewer'), name='agents_one_feedback_per_reviewer')],
            },
        ),
    ]
