# Generated by Django 5.1.15 on 2026-08-14 10:28

import apps.core.models
import django.contrib.postgres.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_claimevidence_providerclaim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('service_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('incorporation', 'Company incorporation'), ('company_secretary', 'Company secretary'), ('registered_address', 'Registered address'), ('accounting', 'Accounting'), ('audit_liaison', 'Audit liaison'), ('bank_account_assist', 'Bank account assistance'), ('tax_filing', 'Tax filing'), ('trademark', 'Trademark'), ('work_visa', 'Work visa')], max_length=32), blank=True, default=list, size=None)),
                ('engagement_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Set only by NNC1 verification. Unverified reviews carry weight 0.')),
                ('status', models.CharField(choices=[('pending_moderation', 'Pending moderation'), ('published', 'Published'), ('hidden', 'Hidden'), ('removed', 'Removed')], db_index=True, default='pending_moderation', max_length=24)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('moderation', models.JSONField(blank=True, default=dict)),
                ('moderation_note', models.TextField(blank=True, help_text='Why a moderator published, hid or removed this. Internal.')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.provider')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to='providers.provider')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.review')),
            ],
            options={
                'verbose_name': 'review reply',
                'verbose_name_plural': 'review replies',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_transparency', models.DecimalField(decimal_places=1, max_digits=2)),
                ('responsiveness', models.DecimalField(decimal_places=1, max_digits=2)),
                ('bank_support', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('professionalism', models.DecimalField(decimal_places=1, max_digits=2)),
                ('after_sales', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='reviews.review')),
            ],
            options={
                'verbose_name': 'review score',
                'verbose_name_plural': 'review scores',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['provider', 'status', '-published_at'], name='reviews_rev_provide_6f3737_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'created_at'], name='reviews_rev_status_c24b9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('provider', 'author'), name='reviews_one_review_per_author_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('overall__gte', Decimal('1')), ('overall__lte', Decimal('5'))), name='reviews_overall_within_range'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.CheckConstraint(condition=models.Q(('price_transparency__gte', Decimal('1')), ('price_transparency__lte', Decimal('5')), ('responsiveness__gte', Decimal('1')), ('responsiveness__lte', Decimal('5')), ('professionalism__gte', Decimal('1')), ('professionalism__lte', Decimal('5')), ('after_sales__gte', Decimal('1')), ('after_sales__lte', Decimal('5')), models.Q(('bank_support__isnull', True), models.Q(('bank_support__gte', Decimal('1')), ('bank_support__lte', Decimal('5'))), _connector='OR')), name='reviews_scores_within_range'),
        ),
    ]
