# Generated by Django 5.1.15 on 2026-08-15 07:33

import apps.core.models
import apps.core.storage
import apps.reviews.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nnc1Verification',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=apps.core.storage.private_storage, upload_to=apps.reviews.models.nnc1_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('extension', models.CharField(max_length=8)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Scan pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan error'), ('skipped', 'Scan skipped by a reviewer')], db_index=True, default='pending', max_length=16)),
                ('scan_detail', models.CharField(blank=True, max_length=255)),
                ('scanner', models.CharField(blank=True, max_length=32)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('declared_company_name', models.CharField(blank=True, max_length=255)),
                ('declared_company_no', models.CharField(blank=True, max_length=32)),
                ('declared_secretary_name', models.CharField(blank=True, max_length=255)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('agent_run_id_ref', models.UUIDField(blank=True, help_text='AgentRun that produced `extracted`. A plain UUID until P4-3 creates the table.', null=True)),
                ('match_method', models.CharField(choices=[('exact', 'Exact (after normalisation)'), ('fuzzy', 'Similar'), ('none', 'No match'), ('manual', 'Decided by a reviewer')], default='none', max_length=16)),
                ('match_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('matched_licence_no', models.CharField(blank=True, max_length=32)),
                ('match_detail', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(choices=[('needs_human', 'Needs a reviewer'), ('passed', 'Verified'), ('failed', 'Not verified')], db_index=True, default='needs_human', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Why the reviewer passed or failed it.')),
                ('purge_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='reviews.review')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NNC1 verification',
                'verbose_name_plural': 'NNC1 verifications',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['result', 'created_at'], name='reviews_nnc_result_f352e0_idx')],
            },
        ),
    ]
