# Generated by Django 5.1.15 on 2026-08-15 15:23

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_claimevidence_providerclaim_and_more'),
        ('reviews', '0002_nnc1verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ground', models.CharField(choices=[('not_a_customer', 'The reviewer was never our client'), ('factually_wrong', 'Contains a factual error'), ('personal_data', 'Discloses personal data'), ('defamatory', 'Defamatory or abusive'), ('competitor', 'Posted by a competitor'), ('other', 'Other')], max_length=24)),
                ('reason', models.TextField(help_text="The company's case, in its own words.")),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('ai_arbitration_draft', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('keep', 'Keep the review as it is'), ('amend', 'Hidden pending amendment by the author'), ('hide', 'Hide the review'), ('remove', 'Remove the review')], db_index=True, default='', max_length=16)),
                ('decision_note', models.TextField(blank=True, help_text='Why the moderator decided this. Shown to the company.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='providers.provider')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='reviews.review')),
            ],
            options={
                'verbose_name': 'dispute',
                'verbose_name_plural': 'disputes',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['decision', 'due_at'], name='reviews_dis_decisio_352fc6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('decision', '')), fields=('review',), name='reviews_one_open_dispute_per_review')],
            },
        ),
    ]
